---

- name: PLAY-START
  hosts: node1
  gather_facts: no
  become: yes
  become_user: root

  tasks:
    - name: Install nginx web server on ubuntu server
      apt:
        name: nginx
        state: present
      notify:
        - start nginx

    - name: Insert Index Page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html

  handlers:
   - name: start nginx
     service: name=nginx state=started
